//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Space.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COMPILATION_ERRORS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COMPILATION_ERRORS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Space.Language.Resources.COMPILATION_ERRORS", typeof(COMPILATION_ERRORS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE1: Invalid execution tree, the node type does not exist. Actual node type {0}.
        /// </summary>
        internal static string CE1 {
            get {
                return ResourceManager.GetString("CE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE10: Error in &apos;lower&apos; function..
        /// </summary>
        internal static string CE10 {
            get {
                return ResourceManager.GetString("CE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE11: Aggregation function without &apos;apply window of&apos;..
        /// </summary>
        internal static string CE11 {
            get {
                return ResourceManager.GetString("CE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE12: Error in &apos;count&apos; function..
        /// </summary>
        internal static string CE12 {
            get {
                return ResourceManager.GetString("CE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE13: Aggregation function without &apos;apply window of&apos;..
        /// </summary>
        internal static string CE13 {
            get {
                return ResourceManager.GetString("CE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE14: Error in &apos;sum&apos; function..
        /// </summary>
        internal static string CE14 {
            get {
                return ResourceManager.GetString("CE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE15: Error in &apos;apply window of&apos; function..
        /// </summary>
        internal static string CE15 {
            get {
                return ResourceManager.GetString("CE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE16: Error in &apos;top&apos; function..
        /// </summary>
        internal static string CE16 {
            get {
                return ResourceManager.GetString("CE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE17: Error in &apos;top&apos; function.&quot;.
        /// </summary>
        internal static string CE17 {
            get {
                return ResourceManager.GetString("CE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE10: Error in &apos;buffer with time and size&apos; function..
        /// </summary>
        internal static string CE18 {
            get {
                return ResourceManager.GetString("CE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE19: Error in &apos;where&apos; function..
        /// </summary>
        internal static string CE19 {
            get {
                return ResourceManager.GetString("CE19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE2: Invalid parameter..
        /// </summary>
        internal static string CE2 {
            get {
                return ResourceManager.GetString("CE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE20: Error in &apos;select for result&apos; function..
        /// </summary>
        internal static string CE20 {
            get {
                return ResourceManager.GetString("CE20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE21: Error in &apos;select&apos; function..
        /// </summary>
        internal static string CE21 {
            get {
                return ResourceManager.GetString("CE21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE22: Error in &apos;select&apos; function..
        /// </summary>
        internal static string CE22 {
            get {
                return ResourceManager.GetString("CE22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE23: Error in &apos;select&apos; function..
        /// </summary>
        internal static string CE23 {
            get {
                return ResourceManager.GetString("CE23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE24: More than one alias with the same name, check the projection..
        /// </summary>
        internal static string CE24 {
            get {
                return ResourceManager.GetString("CE24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE25: More than one alias with the same name, the group by sentence..
        /// </summary>
        internal static string CE25 {
            get {
                return ResourceManager.GetString("CE25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE26: Error in &apos;group by&apos; function..
        /// </summary>
        internal static string CE26 {
            get {
                return ResourceManager.GetString("CE26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE27: Error in &apos;group by&apos; function..
        /// </summary>
        internal static string CE27 {
            get {
                return ResourceManager.GetString("CE27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE28: Error in &apos;merge&apos; function..
        /// </summary>
        internal static string CE28 {
            get {
                return ResourceManager.GetString("CE28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE29: Cannot get the value of the object property {0}..
        /// </summary>
        internal static string CE29 {
            get {
                return ResourceManager.GetString("CE29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE3: Value type of function &apos;left&apos; must be string..
        /// </summary>
        internal static string CE3 {
            get {
                return ResourceManager.GetString("CE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE30: Error with the Message of the event..
        /// </summary>
        internal static string CE30 {
            get {
                return ResourceManager.GetString("CE30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE31: Cannot get the event sub-field {0}..
        /// </summary>
        internal static string CE31 {
            get {
                return ResourceManager.GetString("CE31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE32: Cannot get the event field {0}..
        /// </summary>
        internal static string CE32 {
            get {
                return ResourceManager.GetString("CE32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE33: Cannot get the event part {0}..
        /// </summary>
        internal static string CE33 {
            get {
                return ResourceManager.GetString("CE33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE34: Invalid cast..
        /// </summary>
        internal static string CE34 {
            get {
                return ResourceManager.GetString("CE34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE35: Error with &apos;like&apos; operation..
        /// </summary>
        internal static string CE35 {
            get {
                return ResourceManager.GetString("CE35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE36: Error with &apos;not&apos; operation..
        /// </summary>
        internal static string CE36 {
            get {
                return ResourceManager.GetString("CE36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE37: Error with greater than or equal &apos;&gt;=&apos; operation..
        /// </summary>
        internal static string CE37 {
            get {
                return ResourceManager.GetString("CE37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE38: Error with greater than &apos;&gt;&apos; operation..
        /// </summary>
        internal static string CE38 {
            get {
                return ResourceManager.GetString("CE38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE39: Error with less than or equal &apos;&lt;=&apos; operation..
        /// </summary>
        internal static string CE39 {
            get {
                return ResourceManager.GetString("CE39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE4: Error in &apos;left&apos; function..
        /// </summary>
        internal static string CE4 {
            get {
                return ResourceManager.GetString("CE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE40: Error with less than &apos;&lt;&apos; operation..
        /// </summary>
        internal static string CE40 {
            get {
                return ResourceManager.GetString("CE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE41: Error with not equal &apos;!=&apos; operation..
        /// </summary>
        internal static string CE41 {
            get {
                return ResourceManager.GetString("CE41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE42: Error with equal &apos;==&apos; operation..
        /// </summary>
        internal static string CE42 {
            get {
                return ResourceManager.GetString("CE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE43: Error with substract &apos;-&apos; operation for timespan..
        /// </summary>
        internal static string CE43 {
            get {
                return ResourceManager.GetString("CE43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE44: Error with substract &apos;-&apos; operation..
        /// </summary>
        internal static string CE44 {
            get {
                return ResourceManager.GetString("CE44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE45: Error with negate &apos;-&apos; operation..
        /// </summary>
        internal static string CE45 {
            get {
                return ResourceManager.GetString("CE45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE46: Error with &apos;and&apos; operation..
        /// </summary>
        internal static string CE46 {
            get {
                return ResourceManager.GetString("CE46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE47: Error with &apos;or&apos; operation..
        /// </summary>
        internal static string CE47 {
            get {
                return ResourceManager.GetString("CE47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE48: Error with datetime or timespan &apos;{0}&apos; function..
        /// </summary>
        internal static string CE48 {
            get {
                return ResourceManager.GetString("CE48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE49: Cannot get the property &apos;{0}&apos;..
        /// </summary>
        internal static string CE49 {
            get {
                return ResourceManager.GetString("CE49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE5: Value type of function &apos;right&apos; must be string..
        /// </summary>
        internal static string CE5 {
            get {
                return ResourceManager.GetString("CE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE50: Cannot call &apos;key&apos; variable without a group by expression..
        /// </summary>
        internal static string CE50 {
            get {
                return ResourceManager.GetString("CE50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE51: Cannot get the &apos;{0}&apos; of &apos;group by&apos;..
        /// </summary>
        internal static string CE51 {
            get {
                return ResourceManager.GetString("CE51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE52: Cannot get &apos;{0}&apos; of &apos;group by&apos;..
        /// </summary>
        internal static string CE52 {
            get {
                return ResourceManager.GetString("CE52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE53: Cannot get the value of one of the groups specified in &apos;group by&apos; sentence..
        /// </summary>
        internal static string CE53 {
            get {
                return ResourceManager.GetString("CE53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE54: Error in &apos;order by&apos; function..
        /// </summary>
        internal static string CE54 {
            get {
                return ResourceManager.GetString("CE54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE55: Error in enumerable ToList function.
        /// </summary>
        internal static string CE55 {
            get {
                return ResourceManager.GetString("CE55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE56: Error in dispose expression for list of events.
        /// </summary>
        internal static string CE56 {
            get {
                return ResourceManager.GetString("CE56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE57: Error in dispose expression for a event.
        /// </summary>
        internal static string CE57 {
            get {
                return ResourceManager.GetString("CE57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE58: Error with where for event lock method..
        /// </summary>
        internal static string CE58 {
            get {
                return ResourceManager.GetString("CE58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE59: Error with &apos;where&apos; function..
        /// </summary>
        internal static string CE59 {
            get {
                return ResourceManager.GetString("CE59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE6: Error in &apos;right&apos; function..
        /// </summary>
        internal static string CE6 {
            get {
                return ResourceManager.GetString("CE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE61: Error with the join projection..
        /// </summary>
        internal static string CE61 {
            get {
                return ResourceManager.GetString("CE61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE62: Error in enumerable ToArray function.
        /// </summary>
        internal static string CE62 {
            get {
                return ResourceManager.GetString("CE62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE63: Error with the enumerable join..
        /// </summary>
        internal static string CE63 {
            get {
                return ResourceManager.GetString("CE63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE64: Error in observable switch..
        /// </summary>
        internal static string CE64 {
            get {
                return ResourceManager.GetString("CE64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE65: Compilation context scheduler factory is null..
        /// </summary>
        internal static string CE65 {
            get {
                return ResourceManager.GetString("CE65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE66: Observer type is not defined..
        /// </summary>
        internal static string CE66 {
            get {
                return ResourceManager.GetString("CE66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE67: Error with ObserveOn expression..
        /// </summary>
        internal static string CE67 {
            get {
                return ResourceManager.GetString("CE67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE68: Error with ObserveOn expression..
        /// </summary>
        internal static string CE68 {
            get {
                return ResourceManager.GetString("CE68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE69: Error in observable concat..
        /// </summary>
        internal static string CE69 {
            get {
                return ResourceManager.GetString("CE69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE7: Value type of function &apos;upper&apos; must be string..
        /// </summary>
        internal static string CE7 {
            get {
                return ResourceManager.GetString("CE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE71: Value type of function &apos;abs&apos; must be numeric..
        /// </summary>
        internal static string CE71 {
            get {
                return ResourceManager.GetString("CE71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE72: Error in publish.
        /// </summary>
        internal static string CE72 {
            get {
                return ResourceManager.GetString("CE72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE73: Error in observable join.
        /// </summary>
        internal static string CE73 {
            get {
                return ResourceManager.GetString("CE73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE74: Can&apos;t use constants at the conditions of the ON statement..
        /// </summary>
        internal static string CE74 {
            get {
                return ResourceManager.GetString("CE74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE75: You can only use the equality comparer at the conditions of the ON statement. Found {0}..
        /// </summary>
        internal static string CE75 {
            get {
                return ResourceManager.GetString("CE75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE76: You can only use logical conjunction at the conditions of the ON statement. Found {0}..
        /// </summary>
        internal static string CE76 {
            get {
                return ResourceManager.GetString("CE76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE77: Invalid parameter {0}..
        /// </summary>
        internal static string CE77 {
            get {
                return ResourceManager.GetString("CE77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE78: Invalid types the &apos;isnull&apos; function. Left type {0}, right type {1}.
        /// </summary>
        internal static string CE78 {
            get {
                return ResourceManager.GetString("CE78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE79: Error at the &apos;isnull&apos; function..
        /// </summary>
        internal static string CE79 {
            get {
                return ResourceManager.GetString("CE79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE8: Error in &apos;upper&apos; function..
        /// </summary>
        internal static string CE8 {
            get {
                return ResourceManager.GetString("CE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE81: Error in observable create..
        /// </summary>
        internal static string CE81 {
            get {
                return ResourceManager.GetString("CE81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE82: Error in subscription..
        /// </summary>
        internal static string CE82 {
            get {
                return ResourceManager.GetString("CE82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE83: Error in observable timeout..
        /// </summary>
        internal static string CE83 {
            get {
                return ResourceManager.GetString("CE83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE84: Error in observable catch..
        /// </summary>
        internal static string CE84 {
            get {
                return ResourceManager.GetString("CE84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE85: Error in select for observable group by..
        /// </summary>
        internal static string CE85 {
            get {
                return ResourceManager.GetString("CE85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE86: Error creating a constant expression..
        /// </summary>
        internal static string CE86 {
            get {
                return ResourceManager.GetString("CE86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE9: Value type of function &apos;lower&apos; must be string..
        /// </summary>
        internal static string CE9 {
            get {
                return ResourceManager.GetString("CE9", resourceCulture);
            }
        }
    }
}
