//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Space.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COMPILATION_ERRORS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COMPILATION_ERRORS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Space.Language.Resources.COMPILATION_ERRORS", typeof(COMPILATION_ERRORS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid execution tree, the node type does not exist..
        /// </summary>
        internal static string CE1 {
            get {
                return ResourceManager.GetString("CE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;lower&apos; function.&quot;.
        /// </summary>
        internal static string CE10 {
            get {
                return ResourceManager.GetString("CE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Aggregation function without &apos;apply window of&apos;.&quot;.
        /// </summary>
        internal static string CE11 {
            get {
                return ResourceManager.GetString("CE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;count&apos; function.&quot;.
        /// </summary>
        internal static string CE12 {
            get {
                return ResourceManager.GetString("CE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Aggregation function without &apos;apply window of&apos;.&quot;.
        /// </summary>
        internal static string CE13 {
            get {
                return ResourceManager.GetString("CE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;sum&apos; function.&quot;.
        /// </summary>
        internal static string CE14 {
            get {
                return ResourceManager.GetString("CE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;apply window of&apos; function.&quot;.
        /// </summary>
        internal static string CE15 {
            get {
                return ResourceManager.GetString("CE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;top&apos; function.&quot;.
        /// </summary>
        internal static string CE16 {
            get {
                return ResourceManager.GetString("CE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;top&apos; function.&quot;.
        /// </summary>
        internal static string CE17 {
            get {
                return ResourceManager.GetString("CE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;buffer with time and size&apos; function.&quot;.
        /// </summary>
        internal static string CE18 {
            get {
                return ResourceManager.GetString("CE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;where&apos; function.&quot;.
        /// </summary>
        internal static string CE19 {
            get {
                return ResourceManager.GetString("CE19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stack of variables is empty..
        /// </summary>
        internal static string CE2 {
            get {
                return ResourceManager.GetString("CE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string CE20 {
            get {
                return ResourceManager.GetString("CE20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string CE21 {
            get {
                return ResourceManager.GetString("CE21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string CE22 {
            get {
                return ResourceManager.GetString("CE22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string CE23 {
            get {
                return ResourceManager.GetString("CE23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;More than one alias with the same name, check the projection.&quot;.
        /// </summary>
        internal static string CE24 {
            get {
                return ResourceManager.GetString("CE24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;More than one alias with the same name, the group by sentence.&quot;.
        /// </summary>
        internal static string CE25 {
            get {
                return ResourceManager.GetString("CE25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;group by&apos; function.&quot;.
        /// </summary>
        internal static string CE26 {
            get {
                return ResourceManager.GetString("CE26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;group by&apos; function.&quot;.
        /// </summary>
        internal static string CE27 {
            get {
                return ResourceManager.GetString("CE27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;merge&apos; function.&quot;.
        /// </summary>
        internal static string CE28 {
            get {
                return ResourceManager.GetString("CE28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of the object property {0}..
        /// </summary>
        internal static string CE29 {
            get {
                return ResourceManager.GetString("CE29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type of function &apos;left&apos; must be string..
        /// </summary>
        internal static string CE3 {
            get {
                return ResourceManager.GetString("CE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the Message of the event.&quot;.
        /// </summary>
        internal static string CE30 {
            get {
                return ResourceManager.GetString("CE30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the event sub-field {0}..
        /// </summary>
        internal static string CE31 {
            get {
                return ResourceManager.GetString("CE31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the event field {0}..
        /// </summary>
        internal static string CE32 {
            get {
                return ResourceManager.GetString("CE32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the event part {0}..
        /// </summary>
        internal static string CE33 {
            get {
                return ResourceManager.GetString("CE33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid cast.&quot;.
        /// </summary>
        internal static string CE34 {
            get {
                return ResourceManager.GetString("CE34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;like&apos; operation.&quot;.
        /// </summary>
        internal static string CE35 {
            get {
                return ResourceManager.GetString("CE35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;not&apos; operation.&quot;.
        /// </summary>
        internal static string CE36 {
            get {
                return ResourceManager.GetString("CE36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with greater than or equal &apos;&gt;=&apos; operation.&quot;.
        /// </summary>
        internal static string CE37 {
            get {
                return ResourceManager.GetString("CE37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with greater than &apos;&gt;&apos; operation.&quot;.
        /// </summary>
        internal static string CE38 {
            get {
                return ResourceManager.GetString("CE38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with less than or equal &apos;&lt;=&apos; operation.&quot;.
        /// </summary>
        internal static string CE39 {
            get {
                return ResourceManager.GetString("CE39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;left&apos; function.&quot;.
        /// </summary>
        internal static string CE4 {
            get {
                return ResourceManager.GetString("CE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with less than &apos;&lt;&apos; operation.&quot;.
        /// </summary>
        internal static string CE40 {
            get {
                return ResourceManager.GetString("CE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with not equal &apos;!=&apos; operation..
        /// </summary>
        internal static string CE41 {
            get {
                return ResourceManager.GetString("CE41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with equal &apos;==&apos; operation..
        /// </summary>
        internal static string CE42 {
            get {
                return ResourceManager.GetString("CE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with substract &apos;-&apos; operation for timespan..
        /// </summary>
        internal static string CE43 {
            get {
                return ResourceManager.GetString("CE43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with substract &apos;-&apos; operation..
        /// </summary>
        internal static string CE44 {
            get {
                return ResourceManager.GetString("CE44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with negate &apos;-&apos; operation..
        /// </summary>
        internal static string CE45 {
            get {
                return ResourceManager.GetString("CE45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with &apos;and&apos; operation..
        /// </summary>
        internal static string CE46 {
            get {
                return ResourceManager.GetString("CE46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with &apos;or&apos; operation..
        /// </summary>
        internal static string CE47 {
            get {
                return ResourceManager.GetString("CE47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with datetime or timespan &apos;{0}&apos; function..
        /// </summary>
        internal static string CE48 {
            get {
                return ResourceManager.GetString("CE48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the property &apos;{0}&apos;..
        /// </summary>
        internal static string CE49 {
            get {
                return ResourceManager.GetString("CE49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Value type of function &apos;right&apos; must be string.&quot;.
        /// </summary>
        internal static string CE5 {
            get {
                return ResourceManager.GetString("CE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot call &apos;key&apos; variable without a group by expression.&quot;.
        /// </summary>
        internal static string CE50 {
            get {
                return ResourceManager.GetString("CE50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the &apos;{0}&apos; of &apos;group by&apos;..
        /// </summary>
        internal static string CE51 {
            get {
                return ResourceManager.GetString("CE51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get &apos;{0}&apos; of &apos;group by&apos;..
        /// </summary>
        internal static string CE52 {
            get {
                return ResourceManager.GetString("CE52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of one of the groups specified in &apos;group by&apos; sentence..
        /// </summary>
        internal static string CE53 {
            get {
                return ResourceManager.GetString("CE53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in &apos;order by&apos; function..
        /// </summary>
        internal static string CE54 {
            get {
                return ResourceManager.GetString("CE54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;right&apos; function.&quot;.
        /// </summary>
        internal static string CE6 {
            get {
                return ResourceManager.GetString("CE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Value type of function &apos;upper&apos; must be string.&quot;.
        /// </summary>
        internal static string CE7 {
            get {
                return ResourceManager.GetString("CE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;upper&apos; function.&quot;.
        /// </summary>
        internal static string CE8 {
            get {
                return ResourceManager.GetString("CE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Value type of function &apos;lower&apos; must be string.&quot;.
        /// </summary>
        internal static string CE9 {
            get {
                return ResourceManager.GetString("CE9", resourceCulture);
            }
        }
    }
}
