//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Space.Language.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Space.Language.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class COMPILATION_ERRORS
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Invalid execution tree, the node type does not exist.
		/// </summary>
		public static string CE1 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE1; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'lower' function."
		/// </summary>
		public static string CE10 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE10; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Aggregation function without 'apply window of'."
		/// </summary>
		public static string CE11 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE11; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'count' function."
		/// </summary>
		public static string CE12 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE12; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Aggregation function without 'apply window of'."
		/// </summary>
		public static string CE13 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE13; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'sum' function."
		/// </summary>
		public static string CE14 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE14; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'apply window of' function."
		/// </summary>
		public static string CE15 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE15; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'top' function."
		/// </summary>
		public static string CE16 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE16; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'top' function."
		/// </summary>
		public static string CE17 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE17; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'buffer with time and size' function."
		/// </summary>
		public static string CE18 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE18; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'where' function."
		/// </summary>
		public static string CE19 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE19; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The stack of variables is empty.
		/// </summary>
		public static string CE2 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE2; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'select' function."
		/// </summary>
		public static string CE20 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE20; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'select' function."
		/// </summary>
		public static string CE21 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE21; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'select' function."
		/// </summary>
		public static string CE22 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE22; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'select' function."
		/// </summary>
		public static string CE23 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE23; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"More than one alias with the same name, check the projection."
		/// </summary>
		public static string CE24 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE24; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"More than one alias with the same name, the group by sentence."
		/// </summary>
		public static string CE25 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE25; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'group by' function."
		/// </summary>
		public static string CE26 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE26; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'group by' function."
		/// </summary>
		public static string CE27 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE27; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'merge' function."
		/// </summary>
		public static string CE28 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE28; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the value of the object property {0}.
		/// </summary>
		public static string CE29(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE29, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Value type of function 'left' must be string.
		/// </summary>
		public static string CE3 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE3; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the Message of the event."
		/// </summary>
		public static string CE30 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE30; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the event sub-field {0}.
		/// </summary>
		public static string CE31(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE31, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the event field {0}.
		/// </summary>
		public static string CE32(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE32, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the event part {0}.
		/// </summary>
		public static string CE33(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE33, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Invalid cast."
		/// </summary>
		public static string CE34 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE34; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'like' operation."
		/// </summary>
		public static string CE35 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE35; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'not' operation."
		/// </summary>
		public static string CE36 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE36; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with greater than or equal '>=' operation."
		/// </summary>
		public static string CE37 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE37; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with greater than '>' operation."
		/// </summary>
		public static string CE38 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE38; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with less than or equal '<=' operation."
		/// </summary>
		public static string CE39 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE39; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'left' function."
		/// </summary>
		public static string CE4 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE4; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with less than '<' operation."
		/// </summary>
		public static string CE40 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE40; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with not equal '!=' operation.
		/// </summary>
		public static string CE41 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE41; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with equal '==' operation.
		/// </summary>
		public static string CE42 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE42; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with substract '-' operation for timespan.
		/// </summary>
		public static string CE43 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE43; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with substract '-' operation.
		/// </summary>
		public static string CE44 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE44; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with negate '-' operation.
		/// </summary>
		public static string CE45 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE45; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with 'and' operation.
		/// </summary>
		public static string CE46 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE46; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with 'or' operation.
		/// </summary>
		public static string CE47 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE47; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error with datetime or timespan '{0}' function.
		/// </summary>
		public static string CE48(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE48, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the property '{0}'.
		/// </summary>
		public static string CE49(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE49, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Value type of function 'right' must be string."
		/// </summary>
		public static string CE5 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE5; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Cannot call 'key' variable without a group by expression."
		/// </summary>
		public static string CE50 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE50; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the '{0}' of 'group by'.
		/// </summary>
		public static string CE51(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE51, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get '{0}' of 'group by'.
		/// </summary>
		public static string CE52(object arg0)
		{
			return string.Format(global::Integra.Space.Language.COMPILATION_ERRORS.CE52, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Cannot get the value of one of the groups specified in 'group by' sentence.
		/// </summary>
		public static string CE53 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE53; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string CE54 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE54; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'right' function."
		/// </summary>
		public static string CE6 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE6; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Value type of function 'upper' must be string."
		/// </summary>
		public static string CE7 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE7; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'upper' function."
		/// </summary>
		public static string CE8 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE8; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Value type of function 'lower' must be string."
		/// </summary>
		public static string CE9 { get { return global::Integra.Space.Language.COMPILATION_ERRORS.CE9; } }
	}
}

