//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Space.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParseResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParseResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Space.Language.Resources.ParseResults", typeof(ParseResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Bad permission &apos;{1}&apos;..
        /// </summary>
        internal static string BadPermission {
            get {
                return ResourceManager.GetString("BadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Bad command..
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. The extension &apos;{1}&apos; is defined more than once.
        /// </summary>
        internal static string DuplicateApplyExtension {
            get {
                return ResourceManager.GetString("DuplicateApplyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. The column &apos;{1}&apos; is already defined..
        /// </summary>
        internal static string DuplicateColumn {
            get {
                return ResourceManager.GetString("DuplicateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Duplicate command option {1}.
        /// </summary>
        internal static string DuplicateCommandOption {
            get {
                return ResourceManager.GetString("DuplicateCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Invalid apply extension &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidApplyExtension {
            get {
                return ResourceManager.GetString("InvalidApplyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Invalid action {1}.
        /// </summary>
        internal static string InvalidCommandAction {
            get {
                return ResourceManager.GetString("InvalidCommandAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Invalid option {1}.
        /// </summary>
        internal static string InvalidCommandOption {
            get {
                return ResourceManager.GetString("InvalidCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Invalid system object type {1}.
        /// </summary>
        internal static string InvalidSystemObjectType {
            get {
                return ResourceManager.GetString("InvalidSystemObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. Invalid types. Left type: {1} - Right type: {2}.
        /// </summary>
        internal static string InvalidTypes {
            get {
                return ResourceManager.GetString("InvalidTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. The role &apos;{1}&apos; is specified more than once.
        /// </summary>
        internal static string RepeatedDatabaseRole {
            get {
                return ResourceManager.GetString("RepeatedDatabaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. The system object {1} is specified more than once.
        /// </summary>
        internal static string RepeatedSystemObject {
            get {
                return ResourceManager.GetString("RepeatedSystemObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}. The user &apos;{1}&apos; is specified more than once.
        /// </summary>
        internal static string RepeatedUser {
            get {
                return ResourceManager.GetString("RepeatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All commands were parsed correctly.
        /// </summary>
        internal static string SuccessBatchParse {
            get {
                return ResourceManager.GetString("SuccessBatchParse", resourceCulture);
            }
        }
    }
}
