//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Space.Language.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Space.Language.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class ParseResults
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Bad permission '{1}'.
		/// </summary>
		public static string BadPermission(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.BadPermission, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Bad command.
		/// </summary>
		public static string CommandError(object arg0)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.CommandError, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. The extension '{1}' is defined more than once
		/// </summary>
		public static string DuplicateApplyExtension(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.DuplicateApplyExtension, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. The column '{1}' is already defined.
		/// </summary>
		public static string DuplicateColumn(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.DuplicateColumn, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Duplicate command option {1}
		/// </summary>
		public static string DuplicateCommandOption(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.DuplicateCommandOption, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Invalid apply extension '{1}'
		/// </summary>
		public static string InvalidApplyExtension(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.InvalidApplyExtension, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Invalid action {1}
		/// </summary>
		public static string InvalidCommandAction(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.InvalidCommandAction, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Invalid option {1}
		/// </summary>
		public static string InvalidCommandOption(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.InvalidCommandOption, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Invalid system object type {1}
		/// </summary>
		public static string InvalidSystemObjectType(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.InvalidSystemObjectType, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. Invalid types. Left type: {1} - Right type: {2}
		/// </summary>
		public static string InvalidTypes(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.InvalidTypes, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. The role '{1}' is specified more than once
		/// </summary>
		public static string RepeatedDatabaseRole(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.RepeatedDatabaseRole, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. The system object {1} is specified more than once
		/// </summary>
		public static string RepeatedSystemObject(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.RepeatedSystemObject, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Error code: {0}. The user '{1}' is specified more than once
		/// </summary>
		public static string RepeatedUser(object arg0, object arg1)
		{
			return string.Format(global::Integra.Space.Language.ParseResults.RepeatedUser, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	All commands were parsed correctly
		/// </summary>
		public static string SuccessBatchParse { get { return global::Integra.Space.Language.ParseResults.SuccessBatchParse; } }
	}
}

