//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Space.Language.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Space.Language.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class RUNTIME_ERRORS
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'left' function"
		/// </summary>
		public static string RE1 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE1; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'right' function"
		/// </summary>
		public static string RE10 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE10; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'upper' function"
		/// </summary>
		public static string RE11 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE11; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'lower' function"
		/// </summary>
		public static string RE12 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE12; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'count' function"
		/// </summary>
		public static string RE13 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE13; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error in 'sum' function"
		/// </summary>
		public static string RE14 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE14; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'apply window of' function."
		/// </summary>
		public static string RE15 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE15; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'top' function."
		/// </summary>
		public static string RE16 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE16; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'top' function."
		/// </summary>
		public static string RE17 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE17; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with observable buffer with time and size"
		/// </summary>
		public static string RE18 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE18; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'where' function."
		/// </summary>
		public static string RE19 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE19; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'select' function."
		/// </summary>
		public static string RE2 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE2; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'select' function."
		/// </summary>
		public static string RE20 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE20; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'select' function."
		/// </summary>
		public static string RE21 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE21; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'select' function."
		/// </summary>
		public static string RE22 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE22; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'select' function."
		/// </summary>
		public static string RE23 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE23; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'group by' function."
		/// </summary>
		public static string RE24 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE24; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'group by' function."
		/// </summary>
		public static string RE25 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE25; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'order by' function."
		/// </summary>
		public static string RE26 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE26; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with 'merge' function."
		/// </summary>
		public static string RE27 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE27; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Cannot get the value of the object property {0}.
		/// </summary>
		public static string RE28(object arg0)
		{
			return string.Format(global::Integra.Space.Language.RUNTIME_ERRORS.RE28, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the message of the event."
		/// </summary>
		public static string RE29 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE29; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error getting the subfield {0}.
		/// </summary>
		public static string RE3(object arg0)
		{
			return string.Format(global::Integra.Space.Language.RUNTIME_ERRORS.RE3, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error getting the field {0}.
		/// </summary>
		public static string RE30(object arg0)
		{
			return string.Format(global::Integra.Space.Language.RUNTIME_ERRORS.RE30, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error getting the part {0}.
		/// </summary>
		public static string RE31(object arg0)
		{
			return string.Format(global::Integra.Space.Language.RUNTIME_ERRORS.RE31, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the unbox operation"
		/// </summary>
		public static string RE32 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE32; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the convert operation"
		/// </summary>
		public static string RE33 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE33; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the like operation with two wildcards"
		/// </summary>
		public static string RE34 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE34; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the like operation with left wildcard"
		/// </summary>
		public static string RE35 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE35; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the like operation with right wildcard"
		/// </summary>
		public static string RE36 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE36; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the like operation without wildcards"
		/// </summary>
		public static string RE37 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE37; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the 'not' operation"
		/// </summary>
		public static string RE38 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE38; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the greater than or equal operation '>='"
		/// </summary>
		public static string RE39 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE39; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the greater than operation '>'"
		/// </summary>
		public static string RE4 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE4; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the less than or equal operation '<='"
		/// </summary>
		public static string RE40 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE40; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the less operation '<'"
		/// </summary>
		public static string RE41 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE41; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the not equal operation '!='"
		/// </summary>
		public static string RE42 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE42; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the equal operation '=='"
		/// </summary>
		public static string RE43 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE43; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the substract operation '-' for timespan"
		/// </summary>
		public static string RE44 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE44; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the substract operation '-'"
		/// </summary>
		public static string RE45 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE45; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the negate operation '-'"
		/// </summary>
		public static string RE46 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE46; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the and operation 'and'"
		/// </summary>
		public static string RE47 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE47; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the or operation 'or'"
		/// </summary>
		public static string RE48 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE48; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the get property of a date type operation"
		/// </summary>
		public static string RE49 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE49; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the get property operation"
		/// </summary>
		public static string RE5 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE5; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the get group key operation"
		/// </summary>
		public static string RE50 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE50; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the get group key property operation"
		/// </summary>
		public static string RE51 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE51; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	"Error with the get group key property value operation"
		/// </summary>
		public static string RE52 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE52; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE53 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE53; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE54 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE54; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE6 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE6; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE7 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE7; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE8 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE8; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	
		/// </summary>
		public static string RE9 { get { return global::Integra.Space.Language.RUNTIME_ERRORS.RE9; } }
	}
}

