//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Space.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RUNTIME_ERRORS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RUNTIME_ERRORS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Space.Language.Resources.RUNTIME_ERRORS", typeof(RUNTIME_ERRORS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;left&apos; function&quot;.
        /// </summary>
        internal static string RE1 {
            get {
                return ResourceManager.GetString("RE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;right&apos; function&quot;.
        /// </summary>
        internal static string RE10 {
            get {
                return ResourceManager.GetString("RE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;upper&apos; function&quot;.
        /// </summary>
        internal static string RE11 {
            get {
                return ResourceManager.GetString("RE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;lower&apos; function&quot;.
        /// </summary>
        internal static string RE12 {
            get {
                return ResourceManager.GetString("RE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;count&apos; function&quot;.
        /// </summary>
        internal static string RE13 {
            get {
                return ResourceManager.GetString("RE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error in &apos;sum&apos; function&quot;.
        /// </summary>
        internal static string RE14 {
            get {
                return ResourceManager.GetString("RE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;apply window of&apos; function.&quot;.
        /// </summary>
        internal static string RE15 {
            get {
                return ResourceManager.GetString("RE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;top&apos; function.&quot;.
        /// </summary>
        internal static string RE16 {
            get {
                return ResourceManager.GetString("RE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;top&apos; function.&quot;.
        /// </summary>
        internal static string RE17 {
            get {
                return ResourceManager.GetString("RE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with observable buffer with time and size&quot;.
        /// </summary>
        internal static string RE18 {
            get {
                return ResourceManager.GetString("RE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;where&apos; function.&quot;.
        /// </summary>
        internal static string RE19 {
            get {
                return ResourceManager.GetString("RE19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string RE2 {
            get {
                return ResourceManager.GetString("RE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string RE20 {
            get {
                return ResourceManager.GetString("RE20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string RE21 {
            get {
                return ResourceManager.GetString("RE21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string RE22 {
            get {
                return ResourceManager.GetString("RE22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;select&apos; function.&quot;.
        /// </summary>
        internal static string RE23 {
            get {
                return ResourceManager.GetString("RE23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;group by&apos; function.&quot;.
        /// </summary>
        internal static string RE24 {
            get {
                return ResourceManager.GetString("RE24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;group by&apos; function.&quot;.
        /// </summary>
        internal static string RE25 {
            get {
                return ResourceManager.GetString("RE25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;order by&apos; function.&quot;.
        /// </summary>
        internal static string RE26 {
            get {
                return ResourceManager.GetString("RE26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with &apos;merge&apos; function.&quot;.
        /// </summary>
        internal static string RE27 {
            get {
                return ResourceManager.GetString("RE27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot get the value of the object property {0}..
        /// </summary>
        internal static string RE28 {
            get {
                return ResourceManager.GetString("RE28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the message of the event.&quot;.
        /// </summary>
        internal static string RE29 {
            get {
                return ResourceManager.GetString("RE29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error getting the subfield {0}..
        /// </summary>
        internal static string RE3 {
            get {
                return ResourceManager.GetString("RE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error getting the field {0}..
        /// </summary>
        internal static string RE30 {
            get {
                return ResourceManager.GetString("RE30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error getting the part {0}..
        /// </summary>
        internal static string RE31 {
            get {
                return ResourceManager.GetString("RE31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the unbox operation&quot;.
        /// </summary>
        internal static string RE32 {
            get {
                return ResourceManager.GetString("RE32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the convert operation&quot;.
        /// </summary>
        internal static string RE33 {
            get {
                return ResourceManager.GetString("RE33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the like operation with two wildcards&quot;.
        /// </summary>
        internal static string RE34 {
            get {
                return ResourceManager.GetString("RE34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the like operation with left wildcard&quot;.
        /// </summary>
        internal static string RE35 {
            get {
                return ResourceManager.GetString("RE35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the like operation with right wildcard&quot;.
        /// </summary>
        internal static string RE36 {
            get {
                return ResourceManager.GetString("RE36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the like operation without wildcards&quot;.
        /// </summary>
        internal static string RE37 {
            get {
                return ResourceManager.GetString("RE37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the &apos;not&apos; operation&quot;.
        /// </summary>
        internal static string RE38 {
            get {
                return ResourceManager.GetString("RE38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the greater than or equal operation &apos;&gt;=&apos;&quot;.
        /// </summary>
        internal static string RE39 {
            get {
                return ResourceManager.GetString("RE39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the greater than operation &apos;&gt;&apos;&quot;.
        /// </summary>
        internal static string RE4 {
            get {
                return ResourceManager.GetString("RE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the less than or equal operation &apos;&lt;=&apos;&quot;.
        /// </summary>
        internal static string RE40 {
            get {
                return ResourceManager.GetString("RE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the less operation &apos;&lt;&apos;&quot;.
        /// </summary>
        internal static string RE41 {
            get {
                return ResourceManager.GetString("RE41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the not equal operation &apos;!=&apos;&quot;.
        /// </summary>
        internal static string RE42 {
            get {
                return ResourceManager.GetString("RE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the equal operation &apos;==&apos;&quot;.
        /// </summary>
        internal static string RE43 {
            get {
                return ResourceManager.GetString("RE43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the substract operation &apos;-&apos; for timespan&quot;.
        /// </summary>
        internal static string RE44 {
            get {
                return ResourceManager.GetString("RE44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the substract operation &apos;-&apos;&quot;.
        /// </summary>
        internal static string RE45 {
            get {
                return ResourceManager.GetString("RE45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the negate operation &apos;-&apos;&quot;.
        /// </summary>
        internal static string RE46 {
            get {
                return ResourceManager.GetString("RE46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the and operation &apos;and&apos;&quot;.
        /// </summary>
        internal static string RE47 {
            get {
                return ResourceManager.GetString("RE47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the or operation &apos;or&apos;&quot;.
        /// </summary>
        internal static string RE48 {
            get {
                return ResourceManager.GetString("RE48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the get property of a date type operation&quot;.
        /// </summary>
        internal static string RE49 {
            get {
                return ResourceManager.GetString("RE49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the get property operation&quot;.
        /// </summary>
        internal static string RE5 {
            get {
                return ResourceManager.GetString("RE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the get group key operation&quot;.
        /// </summary>
        internal static string RE50 {
            get {
                return ResourceManager.GetString("RE50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the get group key property operation&quot;.
        /// </summary>
        internal static string RE51 {
            get {
                return ResourceManager.GetString("RE51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error with the get group key property value operation&quot;.
        /// </summary>
        internal static string RE52 {
            get {
                return ResourceManager.GetString("RE52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE53 {
            get {
                return ResourceManager.GetString("RE53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE54 {
            get {
                return ResourceManager.GetString("RE54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE6 {
            get {
                return ResourceManager.GetString("RE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE7 {
            get {
                return ResourceManager.GetString("RE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE8 {
            get {
                return ResourceManager.GetString("RE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE9 {
            get {
                return ResourceManager.GetString("RE9", resourceCulture);
            }
        }
    }
}
