//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Space.LanguageUnitTests.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string message_type { get; set; }
        public string primary_account_number { get; set; }
        public string retrieval_reference_number { get; set; }
        public System.Guid id_test { get; set; }
        public long relative_time { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
